name: release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          name: linux-binary
          path: assets/

      - name: Pre-Upload Setup
        run: |
          chmod +x assets/Indigo
          mv assets Indigo
          tar -cJvf Indigo-${{ github.ref_name }}-linux.tar.xz
          ls -R

      - name: Uploading Files
        uses: softprops/action-gh-release@v1
        with:
          files: Indigo-${{ github.ref_name }}-linux.tar.xz
