name: windows build

on: push

jobs:
  windows:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        compiler: [{ cc: gcc, cxx: g++ }]
        cmake_build_type: [Debug, Release]
    steps:
      - name: Installing GCC
        uses: egor-tensin/setup-mingw@v2

      - name: Installing CMake
        uses: lukka/get-cmake@latest

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Building Project
        env:
          CC: ${{ matrix.compiler.cc }}
          CXX: ${{ matrix.compiler.cxx }}
        run: |
          cmake -B build -G "Ninja"
          cmake --build build
