name: windows-build

on: [push]

jobs:
  windows:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        compiler: [{ cc: gcc, cxx: g++ }, { cc: clang, cxx: clang++ }]
        cmake_build_type: [Debug, Release]
    steps:
      - name: Installing Dependencies
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-${{ matrix.compiler.cc }}
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-cmake

      - run: |
          pacman -R gcc

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Building Project
        env:
          CC: ${{ matrix.compiler.cc }}
          CXX: ${{ matrix.compiler.cxx }}
        run: |
          cmake -B build -G "Ninja"
          cmake --build build
